services:
  pfe-gen-text-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: amd64
        CUDA_MAJOR_VERSION: 12
        CUDA_MINOR_VERSION: 2
        BUILD_TYPE: cublas
    image: pfe-gen-text-service:cuda-12
    ports:
      - "8080:8080"
    environment:
      MODELS_PATH: "/models"
      DEBUG: "true"
      BUILD_TYPE: "cublas"
      CONFIG_FILE: "/tmp/config.yaml"
    volumes:
      - ./models:/models:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c"]
    command: >
      curl -o /tmp/config.yaml https://gist.githubusercontent.com/cort3xt/bad4a4e767122cc2279656ccd9be20d9/raw/2ee721208fc8508f9e4cfea4f85d914f7ce9007a/calme-2.1-phi3.5-4b-i1.yaml &&
      /app/local-ai
